title: Xiang Cheng
description: Virgina Tech Computer Science PhD Student
show_downloads: false
github.is_project_page: false
logo: /assets/img/xiangcheng.png
theme: jekyll-theme-minimal
google_analytics: [UA-117455419-1]
plugins:
  - jekyll-seo-tag